config/routes.rb
Rails.application.routes.draw do
  
  root "home#index"

  get "/about", to: "aboute#index"
  get "/contact", to: "contact#index"
  get "/view", to: "userjobs#list"

  get "/offers", to:  "offers#new"
  post "/offers", to:  "offers#create"

  get "/offers", to:  "offers#new"
  post "/offers", to:  "offers#create"

  get "/login", to:  "sessions#new"
  post "/login", to:  "sessions#create"
  delete "/logout", to:  "sessions#destroy"

  resources :offers, only: [:new, :create, :destroy]
  get "/pay/:bob", to: "charges#new", as: "pay"
  resources :charges, only: [:create]

  get "/list/:id", to: "interesteds#index", as: "list"

  get "/interesteds/:id", to: "interesteds#create", as: "interesteds"
  delete "/interested/:id", to: "interesteds#destroy", as: "interested"

  resources :userjobs, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
  	member do 
  		get "confirm"
  	end
  end
  
  resources :userservices, only: [:new, :create, :show, :edit, :update, :destroy] do
  	member do 
  		get "confirm"
  	end
  end

end

app/models/admin.rb
class Admin < ApplicationRecord

	has_secure_password
	
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	
	validates :title,
				presence: true,
				length: {minimum: 3, maximum: 55}

	has_many :userjobs
	
end

app/models/comment.rb
class Comment < ApplicationRecord
	
	belongs_to :userjobs, optional: true
	belongs_to :userservices, optional: true

	validates :description,
				presence: true,
				length: {minimum: 5, maximum: 255}
end

app/models/interested.rb
class Interested < ApplicationRecord
	
	belongs_to :userjob
	belongs_to :offer
	
end

app/models/offer.rb
class Offer < ApplicationRecord
	
	belongs_to :userservice
	has_many :interesteds
	has_many :userjobs, through: :interesteds

	validates :title,
				presence: true,
				length: {minimum: 3, maximum: 55}

	validates :description,
				presence: true,
				length: {minimum: 5, maximum: 255}
	
end

app/models/userjob.rb
class Userjob < ApplicationRecord
 
	belongs_to :category
	has_many :comment
	has_many :interesteds
	has_many :offers, through: :interesteds

	validates :firstname,
				presence: true,
				length: {minimum: 3, maximum: 55}


	validates :lastname,
				presence: true,
				length: {maximum: 55}

	validates :email,
				presence: true,
				length: {maximum: 255},
				format: {with: /\A([\w\-\.]+@[A-Za-z0-9]+\.[A-Za-z]{2,8})\z/},
				uniqueness: {case_sensitive: false}

	validates :telephone,
				presence: true

	validates :description,
				presence: true,
				length: {maximum: 255}

	validates :price,
				presence: true

	has_secure_password

	has_secure_token :confirmation_token
	has_one_attached :avatar
										
end

app/models/userservice.rb
class Userservice < ApplicationRecord

	has_many :comment
	has_many :offers	

	validates :firstname,
				presence: true,
				length: {minimum: 3, maximum: 55}


	validates :lastname,
				presence: true,
				length: {minimum: 3, maximum: 55}

	validates :email,
				presence: true,
				length: {maximum: 255},
				format: {with: /\A([\w\-\.]+@[A-Za-z0-9]+\.[A-Za-z]{2,8})\z/},
				uniqueness: {case_sensitive: false}

	validates :telephone,
				presence: true
				

	has_secure_password

	has_secure_token :confirmation_token
	has_one_attached :pdp1

end

app/controllers/aboute_controller.rb
class AbouteController < ApplicationController
  def index
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

	before_action :utype, :confirmed_count
	require "stripe"
	Dotenv::Railtie.load

	$amont = 0

	def new
		@amount = $amont = params[:bob]
	end

	def create

		@amount = $amont

		platform_key = Stripe.api_key
		# create customer on a platform
		cus = Stripe::Customer.create({
		  	source: {object: params['stripeTokenType'], exp_month: 10, exp_year: 2022, number: '4242424242424242'},
		  	description: 'Example customer'
		}, platform_key)

		Stripe::Charge.create({
		  	:amount => @amount,
		  	:currency => "eur",
		  	:description => "Charge for ZARAO",
		  	:customer => cus.id
		})

		
		rescue Stripe::CardError => e
		  	flash[:error] = e.message
		  	redirect_to new_charge_path
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  	def index
  		@offer = Offer.new
		@offers = Offer.all
  	end

end

app/controllers/offers_controller.rb
class OffersController < ApplicationController

	before_action :confirmed_count

	def new
		@offer = Offer.new
		@offers = Offer.all
	end

	def create
		o = Offer.new(param)
		unless uroot
			o.userservice = !utype ? current_user : nil
			if o.valid?
				o.save!	
				flash[:notice] = "publication reussie"
				redirect_to root_path
			else
				flash[:error] = "un des donnees est invalid, veuillez le refaire"
				redirect_to root_path
			end
		else
			o.save(validate: false)
		end
		
	end

	def destroy
		if o = Offer.find(params[:id])
			if o.userservice_id == current_user.id || current_user.admin == true
				Interested.all.each do |x|
					if x.offer_id == o.id
						x.destroy
					end
				end
				o.destroy
				flash[:notice] = "suppression avec succes"
				redirect_to root_path
			else
				flash[:error] = "vous n'avez pas le droit de faire ce changement"
				redirect_to root_path
			end
		else
			flash[:error] = "offre introuvable"
			redirect_to root_path
		end
	end

	private

	def param
		return params.require(:offer).permit(:title, :description, :price, :delais)
	end

end

app/helpers/aboute_helper.rb
module AbouteHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/interesteds_helper.rb
module InterestedsHelper
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def log_in(user)
		session[:email] = user.email
	end

	def current_user
		if a = Userjob.find_by(email: session[:email])
			return a
		elsif b = Userservice.find_by(email: session[:email])
			return b
		elsif c = Admin.find_by(email: session[:email])
			return c
		else
			return current_user = nil
		end				
	end

	def signed_in
		return !current_user.nil?
	end

	def log_out
		current_user = nil
		session.delete(:email)
	end

	def root
		unless Userjob.find_by(email: current_user.email) || Userservice.find_by(email: current_user.email)
			unless signed_in && current_user.admin == true
				flash[:error] = "vous n'etes pas autorisee a faire ce changement"
				redirect_to root_path
			end
		end
	end

	def uroot
		unless Userjob.find_by(email: current_user.email) || Userservice.find_by(email: current_user.email)
			signed_in && current_user.admin == true ? true : false
		end
	end

	def utype
		if signed_in
			return Userjob.find_by(email: current_user.email) ? true : false
		else
			return false
		end
	end

	def confirmed_count
		if signed_in
			unless uroot
				unless current_user.confirmed == true
					flash[:error] = "vous devez confirmer votre compte"
					redirect_to root_path
				end
			end
		end
	end

end

app/helpers/userjobs_helper.rb
module UserjobsHelper
end

app/helpers/userservices_helper.rb
module UserservicesHelper
end

app/views/aboute/index.html.erb
<div class="unit-5 overlay" style="background-image: url('images/Fond.jpeg');">
      <div class="container text-center">
        <h2 class="mb-0">A propos</h2>
        <p class="mb-0 unit-6"><a href="<%= root_path %>">Accueil</a> <span class="sep">></span> <span>A propos</span></p>
      </div>
</div>

<div class="site-section bg-light">
<div class="container element-animate">
      <div class="row justify-content-center mb-5">
          <div class="col-md-7 text-center section-heading">
            <h2 class="text-primary heading">L'équipe</h2>
            <br><br><br>
            <p>Une équipe de jeune talent malgache qui vous propose des idées innovantes, et qui veulent apporter leurs vision du "changement" dans le monde du digital .</p>
          </div>
        </div>
      <div class="row">
        <div class="col-md-5 col-lg-3">
          <div class="block-2">
            <div class="flipper">
              <div class="front" style="background-image: url(images/John.JPG);">
                <div class="box">
                  <h2>John</h2>
                  <p>Project chief & Developpeur Front-end</p>
                </div>
              </div>
              <div class="back">
                <!-- back content -->
                <blockquote>
                  <p>&ldquo;Conscient de la complémentarité de mes études de communication et le développement, je suis prêt à toujours me surpasser pour mes propres convictions ainsi que pour me prouver que l'effort et la persévérance est la clé de la réussite!&rdquo;</p>
                </blockquote>
                <div class="author d-flex">
                  <div class="image mr-3 align-self-center">
                    <img src="images/John.JPG" alt="">
                  </div>
                  <div class="name align-self-center"> <span class="position">Developpeur Front-end</span></div>
                </div>
              </div>
            </div>
          </div> <!-- .flip-container -->
        </div>

        <div class="col-md-5 col-lg-3">
          <div class="block-2 ">
            <div class="flipper">
              <div class="front" style="background-image: url(images/Andy.JPG);">
                <div class="box">
                  <h2>Andy</h2>
                  <p>Developpeur Front-end</p>
                </div>
              </div>
              <div class="back">
                <!-- back content -->
                <blockquote>
                  <p>&ldquo;<br><br><br>N'abandonne pas si vite, car la réussite n'aime pas du tout ça...&rdquo;</p>
                </blockquote>
                <div class="author d-flex">
                  <div class="image mr-3 align-self-center">
                    <img src="images/Andy.JPG" alt="">
                  </div>
                  <div class="name align-self-center"> <span class="position">Developpeur Front-end</span></div>
                </div>
              </div>
            </div>
          </div> <!-- .flip-container -->
        </div>

        <div class="col-md-5 col-lg-3">
          <div class="block-2 ">
            <div class="flipper">
              <div class="front" style="background-image: url(images/Sitraka.jpg);">
                <div class="box">
                  <h2>Sitraka</h2>
                  <p>Developpeur Back-end</p>
                </div>
              </div>
              <div class="back">
                <!-- back content -->
                <blockquote>
                  <p>&ldquo;Etant une personne passionné par le code, j'aime la satisfaction d'un travail bien fait et j'aime tester de nouvelles notions. je suis prêt à travailler dans une entreprise et je suis prêt pour donner le meilleur de moi-même&rdquo;</p>
                </blockquote>
                <div class="author d-flex">
                  <div class="image mr-3 align-self-center">
                    <img src="images/Sitraka.jpg" alt="">
                  </div>
                  <div class="name align-self-center"> <span class="position">Developpeur Back-end</span></div>
                </div>
              </div>
            </div>
          </div> <!-- .flip-container -->
        </div>

        <div class="col-md-5 col-lg-3">
          <div class="block-2">
            <div class="flipper">
              <div class="front" style="background-image: url(images/Tolotra.jpg);">
                <div class="box">
                  <h2>Tolotra</h2>
                  <p>Developpeur Full-stack</p>
                </div>
              </div>
              <div class="back">
                <!-- back content -->
                <blockquote>
                  <p>&ldquo;Passionnée par l'informatique, je ne cesse de m'informer de tous ce qui se passe dans ce secteur, qui ne cessera jamais d’évoluer, ce qui me pousse à toujours apprendre, et à etre passion dans tout ce que je fais.&rdquo;</p>
                </blockquote>
                <div class="author d-flex">
                  <div class="image mr-3 align-self-center">
                    <img src="images/Tolotra.jpg" alt="">
                  </div>
                  <div class="name align-self-center"> <span class="position">Developpeur Full-stack</span></div>
                </div>
              </div>
            </div>
          </div> <!-- .flip-container -->
        </div>
      </div>
    </div>
</div>
    <!-- END .block-2 -->


<div class="site-section">
      <div class="container">
        <div class="row justify-content-center text-center mb-5">
          <div class="col-md-6" data-aos="fade" >
            <h2>Questions-Réponses</h2>
          </div>
        </div>

        <div class="row justify-content-center" data-aos="fade" data-aos-delay="100">
          <div class="col-md-8">
            <div class="accordion unit-8" id="accordion">
            <div class="accordion-item">
              <h3 class="mb-0 heading">
                <a class="btn-block" data-toggle="collapse" href="#collapseOne" role="button" aria-expanded="true" aria-controls="collapseOne">Pourquoi "ZARAO" ?<span class="icon"></span></a>
              </h3>
              <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordion">
                <div class="body-text">
                  <p>Nous avons choisi "ZARAO" comme nom de notre site tout simplement parce que le site à pour but principal de partager et promouvoir le talent que possède le peuple malgache, les aider à sortir de la pauvreté en fesant connaître leurs oeuvres dans le monde pour les mettres en relation avec des personnes qui pouraient les aider.</p>
                </div>
              </div>
            </div> <!-- .accordion-item -->
            
            <div class="accordion-item">
              <h3 class="mb-0 heading">
                <a class="btn-block" data-toggle="collapse" href="#collapseTwo" role="button" aria-expanded="false" aria-controls="collapseTwo">Quel est le tarif moyen proposer par le site ?<span class="icon"></span></a>
              </h3>
              <div id="collapseTwo" class="collapse" aria-labelledby="headingOne" data-parent="#accordion">
                <div class="body-text">
                  <p>Vu qu'il y a plusieurs catégories qui sont différents les uns des autres, le tarif varie énormément. <br>Mais que ce soit journalier, mensuel ou contractuel, nous garantissons que le tarif proposé par les inscrits seront négociable !</p>
                </div>
              </div>
            </div> <!-- .accordion-item -->

            <div class="accordion-item">
              <h3 class="mb-0 heading">
                <a class="btn-block" data-toggle="collapse" href="#collapseThree" role="button" aria-expanded="false" aria-controls="collapseThree">Dois-je m'inscrire pour proposer partager mon talent ?  <span class="icon"></span></a>
              </h3>
              <div id="collapseThree" class="collapse" aria-labelledby="headingOne" data-parent="#accordion">
                <div class="body-text">
                  <p>Pour les jeunes qui veulent offrir leurs services, l'inscriptions est obligatoire car il y aura une vérification pour l'authenticité de votre dire, afin de ne pas polluer le site de personnes indésirables!</p>
                </div>
              </div>
            </div> <!-- .accordion-item -->

            <div class="accordion-item">
              <h3 class="mb-0 heading">
                <a class="btn-block" data-toggle="collapse" href="#collapseFour" role="button" aria-expanded="false" aria-controls="collapseFour">Qui pourrais-je contacter en cas de problème ?<span class="icon"></span></a>
              </h3>
              <div id="collapseFour" class="collapse" aria-labelledby="headingOne" data-parent="#accordion">
                <div class="body-text">
                  <p>Dans l'onglet "CONTACT", vous pouvez nous ecrire ainsi que nous appeler en cas de problème, nous sommes aussi ouvert à toutes proposition d'amélioration ou tout simplement de critique ! <br>Nous avons hâte de connaître vos avis :) !</p>
                </div>
              </div>
            </div> <!-- .accordion-item -->

          </div>
          </div>
        </div>
      
      </div>
    </div>

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>Eur <%= @amount %></strong>!</h2>

<%= link_to "Back", root_path %>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount: $<%= @amount %></span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="<%= @amount %>"
          data-locale="auto"></script>
<% end %>

app/views/home/index.html.erb
<div class="site-blocks-cover overlay" style="background-image: url('images/Fond.jpeg');" data-aos="fade" data-stellar-background-ratio="0.5">
      <div class="container">
        <div class="row align-items-center">
          <div class="col-12" data-aos="fade">
            <h1 style="font-family: 'Permanent Marker';">ZARAO</h1>
            
              <div class="row mb-3">
                <div class="col-md-9">
                  <div class="row">
                    
                      <% if (!utype || uroot) && signed_in  %>
                          <div class="col-md-6 mb-3 mb-md-0">
                            <a href="<%= offers_path %>" class="btn btn-primary btn-block"><span class="h5">+</span> Poster un nouvel offre</a>
                          </div>
                      <% end %>
                    
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-md-12">
                  <p class="small" style="font-family: 'Satisfy'; font-size: 18px">"Le partage des expériences, des compétences de chacun <br>et chacune favorise la croissance de l'intelligence collective."</p>
                </div>
              </div>
              
            
          </div>
        </div>
      </div>
</div>
            
            
              <div class="row mb-3">
                <div class="col-md-9">
                  <div class="row">
                    
                      <% if (!utype || uroot) && signed_in  %>
                          <div class="col-md-6 mb-3 mb-md-0">
                            
                          </div>
                      <% end %>
                    
                  </div>
                </div>
              </div>
              
              
            
          </div>
        </div>
      </div>
</div>





<div class="site-section bg-light">
      <div class="container">
        <div class="row">
          <div class="col-md-12 mb-5 mb-md-0" data-aos="fade-up" data-aos-delay="100">
            <h2 class="mb-5 h3">Publications récentes</h2>
            <div class="rounded border jobs-wrap">

              <% @offers.each do |of| %>
              
              <div class="job-item d-block d-md-flex align-items-center">
                <div class="job-details h-100">

                 
                  
                   

                  <div class="p-3 align-self-center">
                      <div class="align-items-center">
                         <h2 class="mr-3 text-black"><%= of.title %><span class="label label-info"></span></h2>
                         <div class="badge-wrap">
                          <span class="bg-warning text-white badge py-2 px-4"><%= Interested.where(offer_id: of.id).length %></span>
                          <span class="bg-danger text-white badge py-2 px-4"><%= of.delais %><span> Semaine</span></span>
                        </div>
                      </div>

                    <div class="mr-3"><%= of.description %></div>
                    <div ><span class="icon-money mr-1"></span> <%= of.price %> Ar</div>
                    <div>
                      <% if signed_in %>
                        <% if of.userservice_id %>
                          <% if Userservice.find(of.userservice_id).email == current_user.email || uroot %>
                            <span><%= link_to "voir les interessés", list_path(of.id) %></span><br>
                            </span><%= link_to "effacer", offer_path(of), method: :delete, data: {confirm: "Voulez vous vraiment effacer cette publication ?"} %></span>
                          <% end %>
                        <% else %>
                            <% if uroot %>
                              <span><%= link_to "voir les interessés", list_path(of.id) %></span><br>
                              </span><%= link_to "effacer", offer_path(of), method: :delete, data: {confirm: "Voulez vous vraiment effacer cette publication ?"} %></span>
                            <% end %>
                        <% end %>
                      <% end %>
                    </div>
                  </div>
                </div>

                <% if utype %>
                <div class="job-category align-self-center">
                  <div class="p-3">
                    <span class="p-2">
                      
                        <% if Interested.find_by(offer_id: of.id, userjob_id: current_user.id) %>
                          <%= link_to "Déjà interessé", interested_path(of.id), method: :delete, class:"btn btn-primary" %>
                        <% else %>
                          <%= link_to "Interessé", interesteds_path(of.id), class:"btn btn-primary" %>
                        <% end %>
                      
          
                    </span>
                  </div>
                </div>
                <% end %>  
              </div>
              <% end %>
            </div>
          </div>



      </div>
    </div>
</div>


<div class="site-section bg-white">
      <div class="container">
        <div class="row align-items-center">
          <div class="col-md-6 order-md-2">
            
              <div class="img-border">
                <a href="https://www.youtube.com/watch?v=HAPv57kUg48" class="popup-vimeo image-play">
                  <span class="icon-wrap">
                    <span class="icon icon-play"></span>
                  </span>
                  <img src="images/larissa.png" alt="Image" class="img-fluid rounded">
                </a>
              </div>
            
          </div>
          <div class="col-md-6 order-md-1">
            <div class="text-left mb-5 section-heading">
              <h2>Une artiste peintre qui n'a d'égal que sa beauté</h2>
            </div>

            <p class="mb-4 h5 font-italic lineheight1-5">&ldquo;Larissa est une jeune peintre qui sait comment manier son pinceau, une vingtaine d'année et déjà tant de talent à faire profiter au monde .&rdquo;</p>
            <p>&mdash; <strong class="text-black font-weight-bold">Larissa</strong>, Talent Malgache</p>
            <p><a href="https://www.youtube.com/watch?v=HAPv57kUg48" class="popup-vimeo text-uppercase">Regarder la video <span class="icon-arrow-right small"></span></a></p>
              
          </div>
        </div>
      
      </div>
</div>

<div class="site-section bg-light">
      <div class="container">
        
        <div class="row align-items-center">
          <div class="col-md-6 order-md-1">
            
              <div class="img-border">
                <a href="https://www.youtube.com/watch?v=YIh4GRGfIsM" class="popup-vimeo image-play">
                  <span class="icon-wrap">
                    <span class="icon icon-play"></span>
                  </span>
                  <img src="images/routedigue.jpg" alt="Image" class="img-fluid rounded">
                </a>
              </div>
            
          </div>
          <div class="col-md-6 order-md-2">
            <div class="text-left mb-5 section-heading">
              <h2>L'art Malgache dans toute sa splendeur</h2>
            </div>

            <p class="mb-4 h5 font-italic lineheight1-5">&ldquo;"Art Malagasy route digue" est une petite entreprise familiale qui fabrique et vend des articles fait mains de toutes sortes, en souvenir pour les touristes du splendeur que possède Madagascar.&rdquo;</p>
            <p>&mdash; <strong class="text-black font-weight-bold">Art M route D</strong>, Talent Malgache</p>
            <p><a href="https://www.youtube.com/watch?v=YIh4GRGfIsM" class="popup-vimeo text-uppercase">Regarder la video  <span class="icon-arrow-right small"></span></a></p>
          </div>
        </div>
      
      </div>
</div>

<div class="site-section bg-white">
      <div class="container">
        <div class="row align-items-center">
          <div class="col-md-6 order-md-2">
            
              <div class="img-border">
                <a href="https://www.youtube.com/watch?v=usojNcNq-C0" class="popup-vimeo image-play">
                  <span class="icon-wrap">
                    <span class="icon icon-play"></span>
                  </span>
                  <img src="images/Karl.jpg" alt="Image" class="img-fluid rounded">
                </a>
              </div>
            
          </div>
          <div class="col-md-6 order-md-1">
            <div class="text-left mb-5 section-heading">
             <h2>Ecologie avec un grand "E"</h2>
            </div>

            <p class="mb-4 h5 font-italic lineheight1-5">&ldquo;Karl est une personne qui possède déja son propre entreprise d'ouvrage en plastique et de sécurité privé, dans tout ses ouvrages, on voit c'est un ferru de l'écologie.&rdquo;</p>
            <p>&mdash; <strong class="text-black font-weight-bold">Karl Fabrice</strong>, Talent Malgache</p>
            <p><a href="https://www.youtube.com/watch?v=usojNcNq-C0" class="popup-youtube text-uppercase">Regarder la video <span class="icon-arrow-right small"></span></a></p>
          </div>
        </div>
      
      </div>
</div>

<div class="site-blocks-cover overlay inner-page" style="background-image: url('images/fondg.jpg');" data-aos="fade" data-stellar-background-ratio="0.5">
      <div class="container">
        <div class="row align-items-center justify-content-center">
          <div class="col-md-6 text-center" data-aos="fade">
            <h1 class="h3 mb-0" style="font-family: 'Dancing Script';">Fais de ta passion un art</h1>
            <p class="h3 text-white mb-5">VIE DE TON TALENT !</p>
            
          </div>
        </div>
      </div>
    </div>
</div>