config/routes.rb
Rails.application.routes.draw do
  
  root "home#index"

  get "/about", to: "aboute#index"
  get "/contact", to: "contact#index"
  get "/view", to: "userjobs#list"

  get "/offers", to:  "offers#new"
  post "/offers", to:  "offers#create"

  get "/offers", to:  "offers#new"
  post "/offers", to:  "offers#create"

  get "/login", to:  "sessions#new"
  post "/login", to:  "sessions#create"
  delete "/logout", to:  "sessions#destroy"

  resources :offers, only: [:new, :create, :destroy]
  get "/pay/:bob", to: "charges#new", as: "pay"
  resources :charges, only: [:create]

  get "/list/:id", to: "interesteds#index", as: "list"

  get "/interesteds/:id", to: "interesteds#create", as: "interesteds"
  delete "/interested/:id", to: "interesteds#destroy", as: "interested"

  resources :userjobs, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
  	member do 
  		get "confirm"
  	end
  end
  
  resources :userservices, only: [:new, :create, :show, :edit, :update, :destroy] do
  	member do 
  		get "confirm"
  	end
  end

end

app/models/admin.rb
class Admin < ApplicationRecord

	has_secure_password
	
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	
	validates :title,
				presence: true,
				length: {minimum: 3, maximum: 55}

	has_many :userjobs
	
end

app/models/comment.rb
class Comment < ApplicationRecord
	
	belongs_to :userjobs, optional: true
	belongs_to :userservices, optional: true

	validates :description,
				presence: true,
				length: {minimum: 5, maximum: 255}
end

app/models/interested.rb
class Interested < ApplicationRecord
	
	belongs_to :userjob
	belongs_to :offer
	
end

app/models/offer.rb
class Offer < ApplicationRecord
	
	belongs_to :userservice
	has_many :interesteds
	has_many :userjobs, through: :interesteds

	validates :title,
				presence: true,
				length: {minimum: 3, maximum: 55}

	validates :description,
				presence: true,
				length: {minimum: 5, maximum: 255}
	
end

app/models/userjob.rb
class Userjob < ApplicationRecord
 
	belongs_to :category
	has_many :comment
	has_many :interesteds
	has_many :offers, through: :interesteds

	validates :firstname,
				presence: true,
				length: {minimum: 3, maximum: 55}


	validates :lastname,
				presence: true,
				length: {maximum: 55}

	validates :email,
				presence: true,
				length: {maximum: 255},
				format: {with: /\A([\w\-\.]+@[A-Za-z0-9]+\.[A-Za-z]{2,8})\z/},
				uniqueness: {case_sensitive: false}

	validates :telephone,
				presence: true

	validates :description,
				presence: true,
				length: {maximum: 255}

	validates :price,
				presence: true

	has_secure_password

	has_secure_token :confirmation_token
	has_one_attached :avatar
										
end

app/models/userservice.rb
class Userservice < ApplicationRecord

	has_many :comment
	has_many :offers	

	validates :firstname,
				presence: true,
				length: {minimum: 3, maximum: 55}


	validates :lastname,
				presence: true,
				length: {minimum: 3, maximum: 55}

	validates :email,
				presence: true,
				length: {maximum: 255},
				format: {with: /\A([\w\-\.]+@[A-Za-z0-9]+\.[A-Za-z]{2,8})\z/},
				uniqueness: {case_sensitive: false}

	validates :telephone,
				presence: true
				

	has_secure_password

	has_secure_token :confirmation_token
	has_one_attached :pdp1

end

app/controllers/aboute_controller.rb
class AbouteController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  	def index
  		@offer = Offer.new
		@offers = Offer.all
  	end

end

app/helpers/aboute_helper.rb
module AbouteHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/interesteds_helper.rb
module InterestedsHelper
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def log_in(user)
		session[:email] = user.email
	end

	def current_user
		if a = Userjob.find_by(email: session[:email])
			return a
		elsif b = Userservice.find_by(email: session[:email])
			return b
		elsif c = Admin.find_by(email: session[:email])
			return c
		else
			return current_user = nil
		end				
	end

	def signed_in
		return !current_user.nil?
	end

	def log_out
		current_user = nil
		session.delete(:email)
	end

	def root
		unless Userjob.find_by(email: current_user.email) || Userservice.find_by(email: current_user.email)
			unless signed_in && current_user.admin == true
				flash[:error] = "vous n'etes pas autorisee a faire ce changement"
				redirect_to root_path
			end
		end
	end

	def uroot
		unless Userjob.find_by(email: current_user.email) || Userservice.find_by(email: current_user.email)
			signed_in && current_user.admin == true ? true : false
		end
	end

	def utype
		if signed_in
			return Userjob.find_by(email: current_user.email) ? true : false
		else
			return false
		end
	end

	def confirmed_count
		if signed_in
			unless uroot
				unless current_user.confirmed == true
					flash[:error] = "vous devez confirmer votre compte"
					redirect_to root_path
				end
			end
		end
	end

end

app/helpers/userjobs_helper.rb
module UserjobsHelper
end

app/helpers/userservices_helper.rb
module UserservicesHelper
end

app/views/layouts/_footer.html.erb
<footer class="site-footer">
      <div class="container">
        

        <div class="row">
          <div class="col-md-4" style="padding-left: 150px;">
            <h3 class="footer-heading mb-4 text-white">A propos</h3>
            <p>Un site qui va promouvoir votre talent à son juste place dans la société.</p>
            <p><a href="<%= about_path %>" class="btn btn-primary pill text-white px-4">En savoir plus</a></p>
          </div>
         
          
          
          <div class="col-md-4 offset-md-4">
            <div class="col-md-12"><h3 class="footer-heading mb-4 text-white">Réseaux sociaux</h3></div>
              <div class="col-md-12" style="padding-left: 65px; height: 100px;">
                <p>
                  <a href="https://www.facebook.com/yandriamasinavalona" target= 'blank' class="pb-2 pr-2 pl-0" ><span class="icon-facebook"></span></a>
                  <a href="https://www.linkedin.com/in/yves-andriamasinavalona-15367a169/" target= 'blank' class="p-2"><span class="icon-linkedin"></span></a>

                </p>
              </div>
          </div>
        </div>
        <div class="row pt-5 mt-5 text-center">
          <div class="col-md-12">
            <p>
            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
            Copyright &copy; 2019 All Rights Reserved
            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
            </p>
          </div>
          
        </div>
      </div>
</footer>

app/views/layouts/_header.html.erb
<div class="site-navbar-wrap js-site-navbar bg-white">
      
      <div class="container">
        <div class="site-navbar bg-light">
          <div class="py-1">
            <div class="row align-items-center">
              <div class="col-2">
                <h2 class="mb-0 site-logo"><a href="<%= root_path %>"><img src="/images/logo.png" style="height: 100px; width: 130px"></a></h2>
              </div>
              <div class="col-10">
                <nav class="site-navigation text-right" role="navigation">
                  <div class="container">
                    <div class="d-inline-block d-lg-none ml-md-0 mr-auto py-3"><a href="#" class="site-menu-toggle js-menu-toggle text-black"><span class="icon-menu h3"></span></a></div>
                    <ul class="site-menu js-clone-nav d-none d-lg-block">
                <% if signed_in %>
                    <% unless uroot %>
                    		<li><%= link_to "A propos", about_path %></li>
                    		<li><%= link_to "Contact", contact_path %></li>
                    <% end %>
                <% else %>
                    <li><%= link_to "A propos", about_path %></li>
                    <li><%= link_to "Contact", contact_path %></li>
                <% end %>

                <% if signed_in %>
                			
                			<% if Userjob.find_by(email: current_user.email) %>
                        <li class="has-children">
                          <a><%= current_user.email %></a>
                          <ul class="dropdown arrow-top">
                            <li><%= link_to "Editer le profil", edit_userjob_path(current_user.id) %></li>
                            <li><%= link_to "Profil", userjob_path(current_user.id) %></li>
                          </ul>
                        </li>
                      <% elsif Userservice.find_by(email: current_user.email) %>
                          <li><%= link_to "Nos talents", view_path %></li>
                          <li class="has-children">
                          <a><%= current_user.email %></a>
                          <ul class="dropdown arrow-top">
              							<li><%= link_to "Editer le profil", edit_userservice_path(current_user.id)%></li>
              							<li><%= link_to "Voir Profil", userservice_path(current_user.id)%></li>
                            </ul>
                          </li>
                      <% else %>
                        <li class="has-children">
                          <a><%= current_user.email %></a>
                          <ul class="dropdown arrow-top">
                              <li><%= link_to "Listes", userjobs_path %></li>
                          </ul>
                        </li>

							         <% end %>
            						<li><%= link_to "Se déconnecter", logout_path, method: :delete, class:"bg-primary text-white py-3 px-4 rounded" %></li>
            		<% else %>
            					<li class="has-children">
            							<a> Inscription </a>
            	                  <ul class="dropdown arrow-top">
            	                    <li><%=link_to "Partage ton talent", new_userjob_path %></li>
            	                    <li><%=link_to "Trouve le meilleur", new_userservice_path %></li>
            	                  </ul>
            	                </li>
            	                <li><%= link_to "Connexion", login_path, class:"bg-primary text-white py-3 px-4 rounded" %></li>
            				<% end %>
                    
                  </div>
                </nav>
              </div>
            </div>
          </div>
        </div>
      </div>
</div>

<div style="height: 113px;"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ZARAO</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="fonts/icomoon/style.css">
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <link rel="stylesheet" href="css/magnific-popup.css">
    <link rel="stylesheet" href="css/jquery-ui.css">
    <link rel="stylesheet" href="css/owl.carousel.min.css">
    <link rel="stylesheet" href="css/owl.theme.default.min.css">
    <link rel="stylesheet" href="css/bootstrap-datepicker.css">
    <link rel="stylesheet" href="css/animate.css">
    <link rel="stylesheet" href="fonts/flaticon/font/flaticon.css">
    <link rel="stylesheet" href="css/aos.css">
    <link rel="stylesheet" href="css/style.css">
    <link href="https://fonts.googleapis.com/css?family=Permanent+Marker" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet">  
    <link href="https://fonts.googleapis.com/css?family=Dancing+Script" rel="stylesheet"> 
    
  </head>

  <body>
    <div class="site-wrap">

        <div class="site-mobile-menu">
          <div class="site-mobile-menu-header">
            <div class="site-mobile-menu-close mt-3">
              <span class="icon-close2 js-menu-toggle"></span>
            </div>
          </div>
          <div class="site-mobile-menu-body"></div>
        </div> <!-- .site-mobile-menu -->
          
          <% if flash[:error] || flash[:notice] %>
            <script type="text/javascript">alert("<%= flash[:error] %> <%= flash[:notice] %>")</script>
          <% end %>

          <%= render "layouts/header" %>
          
            <%= yield %>
          
          <%= render "layouts/footer" %>
    </div>
    
    <script src="js/jquery-3.3.1.min.js"></script>
    <script src="js/jquery-migrate-3.0.1.min.js"></script>
    <script src="js/jquery-ui.js"></script>
    <script src="js/popper.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="js/owl.carousel.min.js"></script>
    <script src="js/jquery.stellar.min.js"></script>
    <script src="js/jquery.countdown.min.js"></script>
    <script src="js/jquery.magnific-popup.min.js"></script>
    <script src="js/bootstrap-datepicker.min.js"></script>
    <script src="js/aos.js"></script>
    <script src="js/mediaelement-and-player.min.js"></script>
    <script src="js/main.js"></script>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </body>
</html>